### ISSUE TITLE
Držák fotovoltaického panelu

### ISSUE THREAD

**Issue by kaklik** [ODZ-UJF-AV-CR/GEODOS01#3]
Na nový fotovoltaický panel je potřeba udělat nový držák.  Navrhoval bych použít dva symetrické úchyty ze strany krabice. Nějak takto: 

![P_20210915_193728_vHDR_On](https://user-images.githubusercontent.com/1194177/133611093-efbbcf99-344e-4295-9c1b-1bea7c0d6bd0.jpg)

**Comment by kaklik** [comment]
@petrvelicka  zatim navrhl dvě varianty  držáků 

![image](https://user-images.githubusercontent.com/1194177/133480459-6e1163e2-099b-47ab-86e7-763c02633f96.png)


Podložku na připevnění panelu (Rozměr šikmé stěny je stejný jako rozměr panelu). Panel by na podložku musel být přilepen. 
Vzhledem k rozměrům panelu a podložky by bylo nutné tisk rozdělit na více částí. 
![image](https://user-images.githubusercontent.com/1194177/133480534-d2a2636d-fbd7-48e2-8e8b-0854adc58035.png)

Nejblíže původnímu návrhu je první varianta, kterou bych však navrhoval upravit tak, aby: 

- [ ] Šrouby držely panel z boku krabice. Navrhuji použít rozměr M3. 
- [ ] Uchycení panelu bych vyřešil stažením jedním, nebo dvěma nerezovými šrouby M3.

Geometrické rozměry tiskových otvorů pro šrouby lze převzít [například odsud](https://github.com/ThunderFly-aerospace/TF-G2/blob/5dd7c33e797f1e813cab132e38739af15a9d39a1/CAD/bolt_parameters.scad#L31).

**Comment by kakl** [comment]
[https://photos.app.goo.gl/Ssn6bNkHkassB3eN6](https://photos.app.goo.gl/Ssn6bNkHkassB3eN6)

**Comment by petrvelicka** [comment]
Aktualizovano v commitu https://github.com/ODZ-UJF-AV-CR/GEODOS01/commit/8a9ced93de56c70799f06314559b7b110b69e470

Byly pouzity srouby rozmeru M3

**Comment by petrvelicka** [comment]
Nova verze -- podle pripominek. Asi by to uz slo zkusit vytisknout.

**Comment by kaklik** [comment]
> Nova verze -- podle pripominek. Asi by to uz slo zkusit vytisknout.

Vídím teď tohle: 

![image](https://user-images.githubusercontent.com/1194177/134803983-cff8eeb6-4cad-4cac-bd0e-003bd177fc4d.png)

Myslím že by to už mohlo být vytisknutelné. Akorát jsem si ale všiml, že jsi z boku odebral ten druhý šroub, co tam původně byl.  To si nejsem jistý, zda je dobrý nápad, neboť se takhle panel asi otočí dopředu kolem toho jednoho šroubu. 

Asi není nutné aby druhý šroub byl pod tím šroubem jako to bylo, ale možná stačí dva šrouby vedle sebe.  Myslím si ale že na méně než dva šrouby na každé straně to přišroubovat nemůžem. 

@kakl  je někde na ODZ testovací panel a krabice, na kterou to můžem s @petrvelicka  složit?

**Comment by petrvelicka** [comment]
Opraveno v https://github.com/ODZ-UJF-AV-CR/GEODOS01/commit/37dc5497fc9a236ce14df6408016637ce5326a2e

**Comment by kaklik** [comment]
> Opraveno v [37dc549](https://github.com/ODZ-UJF-AV-CR/GEODOS01/commit/37dc5497fc9a236ce14df6408016637ce5326a2e)

Potvrzuji. Nyní vidím dvě díry pro šrouby: 

![image](https://user-images.githubusercontent.com/1194177/134805189-45a3b13a-89b0-422c-8deb-afe53e08d296.png)

Ještě jsem si ale všiml, že všechny otvory jsou nyní šestihranné. Což je tím, že [proměnná $fn je nyní nastavena globálně](https://github.com/ODZ-UJF-AV-CR/GEODOS01/blob/37dc5497fc9a236ce14df6408016637ce5326a2e/cad/SolarHolder_big.scad#L13). Takže veškeré otvory jsou šestihran. Domnívám se, že by otvory měly být kulaté s $fn  20 až 50 a jen zapuštění pro matice šestihranné. 
Také by se mi asi více líbilo, kdyby u solárního panelu byl šroub shora a matice zespodu. Myslím že by se to tak mnohem lépe montovalo a nestála by voda v zahloubení pro matici. Nyní je to přesně opačně.

**Comment by kaklik** [comment]
A asi bych ještě navrhoval stahovací šroub pro uchycení panelu dát blíže k volnému konci zářezu, než k jeho začátku, jak je to teď: 

![image](https://user-images.githubusercontent.com/1194177/134805533-855d463d-561e-4652-934a-a2ddfa72ebf9.png)

Důvodem je, aby se vytištený materiál deformoval na větší délce. Tím se myslím zajistí kvalitnější uchycení.

**Comment by petrvelicka** [comment]
Zmeneno. Jen by me zajimalo, zda to vnoreni jde udelat lepe nez pomoci transform([0,0,0]) (v opacnem pripade se pak meni i fn u toho valce pro sroub samotny)

**Comment by kaklik** [comment]
> Zmeneno. Jen by me zajimalo, zda to vnoreni jde udelat lepe nez pomoci transform([0,0,0]) (v opacnem pripade se pak meni i fn u toho valce pro sroub samotny)

Jo ty myslíš tohle: 

			translate([0, 0, 0]){
				$fn=6;

Ano, toho se lze zbavit tak, že tu proměnnou fn nastavíš přímo tomu válci, [který má fn jako parametr](https://en.wikibooks.org/wiki/OpenSCAD_User_Manual/Primitive_Solids#cylinder).

**Comment by petrvelicka** [comment]
Opraveno, ted ten kod vypada "hezceji".

**Comment by kaklik** [comment]
Tak se to vytisklo docela dobře :) 

![IMG_20210927_215307](https://user-images.githubusercontent.com/1194177/134975944-02fa8a0b-d1c7-429e-8c2d-244f49fd0d59.jpg)

Ještě mě při tom napadlo, zda by úhel fotovoltaického panelu neměl vycházet z optimálního nastavení pro [danou zeměpisnou šířku, kde se přístroj bude instalovat](https://www.solarpaneltilt.com/).  Případně asi v nastavení optimalizovaném na zimní provoz, protože v létě bude z panelu elektriky předpokládám hodně. 

Nyní je to ale potřeba složit na to je zřejmě ale potřeba další materiál od @kakl.
