### ISSUE TITLE
Range to 15 MeV

### ISSUE THREAD

**Issue by kakl** [ODZ-UJF-AV-CR/GEODOS01#5]
Vedci chteli upravit detekcni rozsah, tak je treba do vsech novych kusu osazovat odpor R10 12k misto 6k8.
Puvodne byl rozsah do cca 35 MeV. Ted je neco kolem 15 MeV.

**Comment by kaklik** [comment]
R10 a na kterým modulu?

**Comment by kaklik** [comment]
Přesunuto sem: https://github.com/UniversalScientificTechnologies/GEODOS01/issues/22
